### PR TITLE
Improving Documentation on Using BSCANE2 with Murax and OpenOCD

### PR DESCRIPTION
**Pull request by pipsoft**
This is improving our previous documentation on how we where able to connect to the JTAG of a Murax instantiated on an Arty A7 FPGA board. No extra information is added but nicer looking. Replaces simple text readme with formatted README.md. Also gives a PDF version. Lastly, the .cfg was modernized for what OpenOCD exepcts today.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi,

A few things before the merge : 

- Files as cpld/jtagspi.cfg and cpld/xilinx-xc7.cfg should not be integrated in the VexRiscv repo, as they are unmodified and are part of the openocd repo.
- doc/nativeJtag/README.pdf  should not be in the VexRiscv git repo as it is not a text file and quite big (0.5 MB), each edit of it will endup making the repo history "blow up".

Thanks :D

**Comment by pipsoft** [comment]
You are right of course. I removed the 'cpld' directory together with the PDF. Added some extra notes in the 'README.md' where to find the now missing files in the OpenOCD project. I guess, that should to the trick.

**Comment by pipsoft** [comment]
Anything else that should be achieved before this pull can be accepted? I'm happy to help.

**Comment by Dolu1990** [comment]
Thanks for it, all good ^^

**Pull request merged**
