### PR TITLE
Fix DBusSimplePlugin catchAccessFault for store operations.

### PR DESCRIPTION
**Pull request by losfair**
Currently the logic in `DBusSimplePlugin` only raises access faults on loads from DBus, but not stores.

This PR extends access fault checking to stores.

### CODE REVIEW

**Comment by losfair** [comment]
There's a test failure at https://travis-ci.org/github/SpinalHDL/VexRiscv/jobs/749769389#L2950 . The corresponding code is https://github.com/SpinalHDL/VexRiscv/blob/master/src/test/cpp/raw/machineCsr/src/crt.S#L141 .

It seems that the reference trace assumes that storing to a bad address (`0xF00FFF60`) doesn't fault, but it does now. And the new behavior looks correct to me.

I'm not familiar with how the reference trace is generated - is it from a previous version of VexRiscv, or something like a co-simulation model?

**Comment by Dolu1990** [comment]
Hi, 

Ahhhhh i got it
Basicaly, VexRiscv DBusSimplePlugin do not want a response on writes, so it can't generate a store fault exception.
bus read -> bus response -> check error and may trap
bus write -> nothing -> can't trap

Did that to optimise store.

The same is true for DBusCachedPlugin, as it is write through, it do not want to wait for each write response (which can go through a long 30 cycle delay for a DDR) before continuing the programm execution.

make sense ?

Thanks anyway :)

**Comment by Dolu1990** [comment]
> I'm not familiar with how the reference trace is generated - is it from a previous version of VexRiscv, or something like a co-simulation model?

Basicaly, there is a software golden model in main.cpp which is cross checked with VexRiscv hardware simulation. Both need to be updated together ^^

But in the given case, as the patch fix a "wanted feature", i think we can close it.

**Comment by losfair** [comment]
Yeah got it. From the name `catchAccessFault` I assumed that it catches both load and store errors, and I just found that the [documentation](https://github.com/SpinalHDL/VexRiscv#dbussimpleplugin) describes it as "If a memory **read** returns an error, it will fire a trap exception".

Thanks!

**Pull request closed without merging**
