### PR TITLE
Update to SpinalHDL v1.6.1

### PR DESCRIPTION
**Pull request by dnltz**
Signed-off-by: Daniel Schultz <d.schultz@phytec.de>

### CODE REVIEW

**Comment by dnltz** [comment]
@Dolu1990 - Tested this by booting a simulation. Had no time for run regression tests :(

**Comment by Dolu1990** [comment]
Ahhhhh XD

I did the same this morning without seeing your PR yet XD

**Comment by Dolu1990** [comment]
Thanks anyway :)

**Comment by dnltz** [comment]
@Dolu1990 You're welcome :)

**Pull request closed without merging**
