### PR TITLE
Murax on Arty A7-35

### PR DESCRIPTION
**Pull request by sebastien-riou**
a new folder in scripts/murax dedicated to arty a7 board. 
synthesis and programming using vivado batch mode.

WARNING: it contains also the modification from my previous pull request about Murax XIP on the iCE40-HX8K board, sorry for the mess.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks :)

**Comment by Dolu1990** [comment]
So the other pull request should be closed ?

**Comment by sebastien-riou** [comment]
Hi, yes the other can be closed.
One thing for arty: some tcl files are missing, I don't understand why they are not included in the commit, looking at it...

**Comment by sebastien-riou** [comment]
GIT says:
```
user@lafite:~/dev/vexrisc_fork/VexRiscvArty/scripts/Murax/arty_a7$ git add make_bit_file.tcl
The following paths are ignored by one of your .gitignore files:
scripts/Murax/arty_a7/make_bit_file.tcl
Use -f if you really want to add them.

```

Do you have something against tcl files being committed in this repo ?

**Comment by Dolu1990** [comment]
i have nothing against it, likely the gitignore is to restrictive about it

**Pull request merged**
