### PR TITLE
Update to SpinalHDL 1.6

### PR DESCRIPTION
**Pull request by dnltz**
This PR adds the missing brackets to the Bool.

Not sure if updating the build.sbt is wanted.

### CODE REVIEW

**Comment by dnltz** [comment]
@Dolu1990 woof

**Comment by Dolu1990** [comment]
Hi ^^

Sorry for the delay, i was AFK 1 week in travel XD

Hmm, i would say, nothing should be merged into master, excepted dev, and it seems that thoes issues are already fixed in dev.

let's me merge dev into master :)

**Comment by Dolu1990** [comment]
I merged dev into master, normaly, all should be fine (and this pr can be closed ?)

**Comment by dnltz** [comment]
I was not aware of the dev branch. Thanks for merging!

**Comment by Dolu1990** [comment]
No worries ^^

**Pull request closed without merging**
