### PR TITLE
Add uinstret support.

### PR DESCRIPTION
**Pull request by tomverbeure**

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks :D

It trigger a Unspecified value parameter uinstretAccess.
I'm totaly fine with just giving a default value to the added xxxAccess in the CsrConfig class to avoid backward compatibility issues :)

**Comment by Dolu1990** [comment]
(default being CsrAccess.NONE)

**Comment by tomverbeure** [comment]
I'll add it!

**Comment by tomverbeure** [comment]
Default value added...

**Comment by Dolu1990** [comment]
Thanks :)

**Pull request merged**
